### ISSUE TITLE
Methods marked with @UiThread must be executed on the main thread.

### ISSUE THREAD

**Issue by jeremypng** [tcking/GPlayer#4]
I think I am hitting this trying to get the gplayer code to run:
https://github.com/flutter/flutter/issues/34993

D/ViewRootImpl@5833937[MainActivity]( 6485): ViewPostIme pointer 1
E/AndroidRuntime( 6485): FATAL EXCEPTION: GiraffePlayerInternal:Handler
E/AndroidRuntime( 6485): Process: asaptruck.cspire.com.asap_truck, PID: 6485
E/AndroidRuntime( 6485): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: GiraffePlayerInternal:Handler
E/AndroidRuntime( 6485): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:807)
E/AndroidRuntime( 6485): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:697)
E/AndroidRuntime( 6485): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
E/AndroidRuntime( 6485): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:172)
E/AndroidRuntime( 6485): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:117)
E/AndroidRuntime( 6485): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:226)
E/AndroidRuntime( 6485): 	at com.github.tcking.gplayer.QueuingEventSink.maybeFlush(QueuingEventSink.java:63)
E/AndroidRuntime( 6485): 	at com.github.tcking.gplayer.QueuingEventSink.success(QueuingEventSink.java:42)
E/AndroidRuntime( 6485): 	at com.github.tcking.gplayer.FlutterPlayerListener.onTargetStateChange(FlutterPlayerListener.java:97)
E/AndroidRuntime( 6485): 	at com.github.tcking.gplayer.GiraffePlayer$2.run(GiraffePlayer.java:232)
E/AndroidRuntime( 6485): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 6485): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6485): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime( 6485): 	at android.os.HandlerThread.run(HandlerThread.java:65)
D/ViewRootImpl@5833937[MainActivity]( 6485): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 6485): prepareNavigationBarInfo() DecorView@4f1b299[MainActivity]
D/InputMethodManager( 6485): getNavigationBarColor() -855310
I/Process ( 6485): Sending signal. PID: 6485 SIG: 9

**Comment by jeremypng** [comment]
Nevermind. I was using the build on pub.dev. Wasn’t using your latest patch. It works now.
