### ISSUE TITLE
when i play video then i get this error 🤔

### ISSUE THREAD

**Issue by vitulgoyani** [tcking/GPlayer#5]
```
E/AndroidRuntime(19606): FATAL EXCEPTION: GiraffePlayerInternal:Handler
E/AndroidRuntime(19606): Process: test.blocdemowithapi, PID: 19606
E/AndroidRuntime(19606): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: GiraffePlayerInternal:Handler
E/AndroidRuntime(19606): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:807)
E/AndroidRuntime(19606): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:697)
E/AndroidRuntime(19606): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
E/AndroidRuntime(19606): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:172)
E/AndroidRuntime(19606): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:117)
E/AndroidRuntime(19606): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:226)
E/AndroidRuntime(19606): 	at com.github.tcking.gplayer.QueuingEventSink.maybeFlush(QueuingEventSink.java:63)
E/AndroidRuntime(19606): 	at com.github.tcking.gplayer.QueuingEventSink.success(QueuingEventSink.java:42)
E/AndroidRuntime(19606): 	at com.github.tcking.gplayer.FlutterPlayerListener.onTargetStateChange(FlutterPlayerListener.java:97)
E/AndroidRuntime(19606): 	at com.github.tcking.gplayer.GiraffePlayer$2.run(GiraffePlayer.java:232)
E/AndroidRuntime(19606): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(19606): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19606): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(19606): 	at android.os.HandlerThread.run(HandlerThread.java:65)
I/Process (19606): Sending signal. PID: 19606 SIG: 9
```

**Comment by tcking** [comment]
pull for update or using `gplayer: ^0.0.2`

**Comment by abimujianto** [comment]
yes, update gplayer version
