### ISSUE TITLE
NullPointerException when running release application

### ISSUE THREAD

**Issue by abozanona** [tcking/GPlayer#8]
When I run a release apk I get this exception after the VIdeoPlayer finishes downloading decoder.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:944)
	at com.github.tcking.gplayer.D.a(:2)
	at com.github.tcking.gplayer.LazyLoadManager.a(:14)
	at com.github.tcking.gplayer.LazyLoadManager.onHandleIntent(:4)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by abimujianto** [comment]
Me too, how to solve it. Please help me. I really need the solution,


java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:944)
	at com.github.tcking.gplayer.g.a(Unknown Source:2)
	at com.github.tcking.gplayer.LazyLoadManager.a(Unknown Source:6)
	at com.github.tcking.gplayer.LazyLoadManager.onHandleIntent(Unknown Source:32)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.os.HandlerThread.run(HandlerThread.java:65)


This is the error

**Comment by abozanona** [comment]
@abimujianto I didn't find a solution for this issue. I had to use [`flutter_ijkplayer`](https://github.com/CaiJingLong/flutter_ijkplayer) instead.

**Comment by abimujianto** [comment]
Do you use androidx for your package flutter?

**Comment by abozanona** [comment]
Yes.

**Comment by abimujianto** [comment]
maybe gplayer not support on androidx ?

**Comment by abozanona** [comment]
I don't think that gplayer doesn't support on androidx. I tried to use gplayer before and after upgrading my project to androidx and the same error happened.

**Comment by abimujianto** [comment]
btw, i tried to release with android 9 its work, try downgrade your android version. its will work

**Comment by usaikoo** [comment]
keep java class in proguard file
see https://github.com/befovy/fijkplayer/pull/98/files
then you will solve all problem thanks. 👍
